try {
    assert 1 == 2;
} catch (e: Exception) {
    println(123);
}